# Generated by Django 6.0.3 on 2026-03-28 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.ImageField(upload_to="produtos/")),
                ("disponivel", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="core.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[
                            ("PP", "PP"),
                            ("P", "P"),
                            ("M", "M"),
                            ("G", "G"),
                            ("GG", "GG"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cor", models.CharField(max_length=50)),
                ("estoque", models.PositiveIntegerField(default=10)),
                (
                    "preco_extra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="core.produto",
                    ),
                ),
            ],
        ),
    ]
