# Generated by Django 6.0.3 on 2026-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AlterModelOptions(
            name="variante",
            options={"verbose_name": "Variante", "verbose_name_plural": "Variantes"},
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produtos/",
                verbose_name="Imagem do Produto",
            ),
        ),
    ]
