# Generated by Django 6.0.3 on 2026-04-01 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_produto_options_alter_variante_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cupom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("welcome", "Bem-vindo"),
                            ("loyalty", "Fidelidade"),
                            ("general", "Geral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "desconto_tipo",
                    models.CharField(
                        choices=[("percent", "%"), ("fixed", "R$")], max_length=10
                    ),
                ),
                ("desconto_valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("valido_ate", models.DateTimeField()),
                ("uso_maximo", models.PositiveIntegerField(default=1)),
                (
                    "minimo_compra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
