# Generated by Django 6.0.3 on 2026-04-10 20:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_cupom_pedido"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={"ordering": ["-criado_em"]},
        ),
        migrations.AlterField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
