# Generated by Django 5.1.5 on 2026-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_pedido_options_alter_pedido_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do cliente"),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cidade/Estado"
                    ),
                ),
                ("texto", models.TextField(verbose_name="Depoimento")),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Foto do cliente",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar no checkout"
                    ),
                ),
            ],
            options={
                "verbose_name": "Depoimento",
                "verbose_name_plural": "Depoimentos",
                "ordering": ["-data"],
            },
        ),
        migrations.AlterModelOptions(
            name="pedido",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="external_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
