# Generated by Django 5.1.5 on 2026-04-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_testimonial_alter_pedido_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=5,
                verbose_name="Avaliação (estrelas)",
            ),
        ),
    ]
