# Generated by Django 5.1.5 on 2026-04-23 01:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_testimonial_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Mostrar no site"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="foto",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Foto do cliente"
            ),
        ),
    ]
