# Generated by Django 5.1.5 on 2026-04-23 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_testimonial_ativo_alter_testimonial_foto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="aprovado",
            field=models.BooleanField(
                default=False, verbose_name="Aprovado pelo admin"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cliente",
            ),
        ),
    ]
