# Generated by Django 5.1.5 on 2026-04-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_testimonial_aprovado_testimonial_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo no site"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 ⭐"),
                    (2, "2 ⭐"),
                    (3, "3 ⭐"),
                    (4, "4 ⭐"),
                    (5, "5 ⭐"),
                ],
                default=5,
                verbose_name="Avaliação",
            ),
        ),
    ]
