# Generated by Django 6.0.3 on 2026-04-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_address_alter_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="pontos_fidelidade",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Pontos de Fidelidade"
            ),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="total_pedidos",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total de Pedidos"
            ),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="ultima_compra",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
