# Generated by Django 6.0.3 on 2026-04-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otpcode_pontos_fidelidade_otpcode_total_pedidos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpcode",
            name="pontos_fidelidade",
        ),
        migrations.RemoveField(
            model_name="otpcode",
            name="total_pedidos",
        ),
        migrations.RemoveField(
            model_name="otpcode",
            name="ultima_compra",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Solteiro(a)"),
                    ("C", "Casado(a)"),
                    ("D", "Divorciado(a)"),
                    ("V", "Viúvo(a)"),
                    ("U", "União Estável"),
                    ("N", "Prefiro não informar"),
                ],
                max_length=1,
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nome_completo",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome Completo"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pontos_fidelidade",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Pontos de Fidelidade"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("N", "Prefiro não informar"),
                ],
                max_length=1,
                verbose_name="Sexo",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_pedidos",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total de Pedidos"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ultima_compra",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Compra"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Endereço Completo"
            ),
        ),
    ]
