# Generated by Django 6.0.3 on 2026-04-06 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_otpcode_pontos_fidelidade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "icon",
                    models.CharField(
                        default="bell", max_length=50, verbose_name="Ícone"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
            },
        ),
    ]
